apiVersion: v1
kind: Secret
metadata:
  name: food-delivery-secret
  namespace: food-delivery
type: Opaque
stringData:
  DB_URL: jdbc:mysql://food-delivery-dev-mysql.ck524guskpa9.us-east-1.rds.amazonaws.com:3306/foodauthdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  DB_USERNAME: admin
  DB_PASSWORD: Admin12345!
  JWT_SECRET: foodDeliverySystemSuperSecretKeyForJwtToken123456