{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-delivery-alb-ingress
  namespace: {{ include "food-delivery.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: {{ join "," .Values.aws.publicSubnets | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: {{ .Values.auth.port }}
          - path: /menu
            pathType: Prefix
            backend:
              service:
                name: menu-service
                port:
                  number: {{ .Values.menu.port }}
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: {{ .Values.order.port }}
          - path: /deliveries
            pathType: Prefix
            backend:
              service:
                name: delivery-service
                port:
                  number: {{ .Values.delivery.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-web
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}