apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ include "food-delivery.namespace" . }}
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.auth.image }}
          ports:
            - containerPort: {{ .Values.auth.port }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: food-delivery-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: food-delivery-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: food-delivery-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: food-delivery-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ include "food-delivery.namespace" . }}
spec:
  selector:
    app: auth-service
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
  type: ClusterIP