apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: {{ include "food-delivery.namespace" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  namespace: {{ include "food-delivery.namespace" . }}
spec:
  selector:
    app: frontend-web
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP